### ISSUE TITLE
É possível emitir uma cobrança com data futura?

### ISSUE THREAD

**Issue by BrunoSzczuk** [djonathanb/unipar-2021-trabalho-plano#8]
Dentro das regras propostas, houve a explicitação de que não é possível registrar uma cobrança para o mesmo contrato caso haja uma cobrança já criada para o mês informado.
Durante o desenvolvimento e testes, surgiu a dúvida da possibilidade de registrar uma cobrança com a data futura, onde hoje, da forma com que foi concebida as funcionalidades, é possível.
Sendo assim, fica a pergunta, é desejável que cobranças sejam lançadas para data futura?

**Comment by djonathanb** [comment]
Não é permitido, pois você precisa saber quais os procedimentos que foram realizados para gerar a cobrança.
